//保存微信返回的用户信息
export  const SAVE_WX_USERINFO = 'SAVE_WX_USERINFO';
export  const SAVE_WX_USERINFO_ACTION = 'SAVE_WX_USERINFO_ACTION';

//login
export const SEND_LOGIN_ACTION = 'SEND_LOGIN_ACTION';
export const SET_SESSIONID_REDUCER = 'SET_LOGIN_REDUCER';
export const CHECK_EXPIRES_ACTION = 'CHECK_EXPIRES_ACTION';
